name: Apply SQL Delta Script to target
on:
  workflow_call:
    inputs:
      target_sql_server:
        required: true
        type: string
      delta_script_name:
        required: true
        type: string
   # secrets:
   #   sql_user_name:
   #     required: false
   #   sql_user_password:
   #     required: false
   
jobs:
  Update_SQL_Server_with_Delta_Script:   
  
   runs-on: self-hosted
   environment: 'Development'
   defaults:
      run:
        working-directory: ${{ github.workspace }}

  # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
     - name: Apply delta inline
       run: cmd.exe /K sqlcmd -S ${{ inputs.target_sql_server }} -i ${{ github.workspace }}\${{ input.delta_script_name }}
