name: Build_dacpac_from_database_server_instance
on:
  workflow_call:
    inputs:
      databasename:
        required: true
        type: string
      outputfilename:
        required: true
        type: string
      branchname:
        required: true
        type: string
  
      
      
jobs:
  Check_env_variable:
    runs-on: self-hosted #windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Run script with branch variable
        run: echo "We are running code for branch - ${{ input.branchname }} " 
        
  Build_dacpac_file_and_add_to_arifacts_env-dev:   
   if: ${{ input.branchname }} == 'env-dev'   
   runs-on: self-hosted #windows-latest
   defaults:
      run:
        shell: cmd
   steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
       
      - name: Run script with branch variable
        run: echo "We are running code for input envirornmnt -  ${{ input.envirornment }} " 
       
      - name: Add sqlpackage to PATH
        uses: coreywebber/setup-sqlpackage@v1
        with:
          sql-version: 14
              
      - name: Build dacpac
        run: sqlpackage.exe /TargetFile:${{ github.workspace }}/dev_${{ inputs.outputfilename }} /Action:Extract /SourceServerName:${{ secrets.Dev_InstanceServerName }} /SourceDatabaseName:${{ inputs.databasename }}
        
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workspace }}/dev_${{ inputs.outputfilename }}
   
  Build_dacpac_file_and_add_to_arifacts_env-qa:   
     if: ${{ input.branchname }} == 'env-qa'   
     runs-on: self-hosted #windows-latest
     defaults:
        run:
          shell: cmd
     steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        - name: Run script with branch variable
          run: echo "We are running code for branch - %GITHUB_REF_NAME%" 
        
        - name: Add sqlpackage to PATH
          uses: coreywebber/setup-sqlpackage@v1
          with:
            sql-version: 14

        - name: Build dacpac
          run: sqlpackage.exe /TargetFile:${{ github.workspace }}/qa_${{ inputs.outputfilename }} /Action:Extract /SourceServerName:${{ secrets.QA_InstanceServerName }} /SourceDatabaseName:${{ inputs.databasename }}
          #run: sqlpackage.exe /TargetFile:${{ github.workspace }}/${{ inputs.outputfilename }} /Action:Extract /SourceServerName:${{ inputs.slqserverinstancename }}\${{ inputs.slqservername }} /SourceDatabaseName:${{ inputs.databasename }}

        - uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: ${{ github.workspace }}/qa_${{ inputs.outputfilename }}
 
  Build_dacpac_file_and_add_to_arifacts_env-prod:   
     if: ${{ input.branchname }} == 'master'   
     runs-on: self-hosted #windows-latest
     defaults:
        run:
          shell: cmd
     steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        - name: Run script with branch variable
          run: echo "We are running code for branch - %GITHUB_REF_NAME%" 
        
        - name: Add sqlpackage to PATH
          uses: coreywebber/setup-sqlpackage@v1
          with:
            sql-version: 14

        - name: Build dacpac
          run: sqlpackage.exe /TargetFile:${{ github.workspace }}/prod_${{ inputs.outputfilename }} /Action:Extract /SourceServerName:${{ secrets.Prod_InstanceServerName }} /SourceDatabaseName:${{ inputs.databasename }}

        - uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: ${{ github.workspace }}/prod_${{ inputs.outputfilename }}
