name: Build_dacpac_from_database_server_instance
on:
  workflow_call:
    inputs:
      outputfilename:
        required: true
        type: string
      slqserverinstancename:
        required: true
        type: string
      slqservername:
        required: true
        type: string
      databasename:
        required: true
        type: string
      
   
jobs:
  Build_dacpac_file_and_add_to_arifacts:   
  
   runs-on: self-hosted #windows-latest
   defaults:
      run:
        shell: cmd
   steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
               
      - name: Add sqlpackage to PATH
        uses: coreywebber/setup-sqlpackage@v1
        with:
          sql-version: 14
              
      - name: Build dacpac
        run: sqlpackage.exe /TargetFile:${{ github.workspace }}/${{ inputs.outputfilename }} /Action:Extract /SourceServerName:${{ inputs.slqserverinstancename }}\${{ inputs.slqservername }} /SourceDatabaseName:${{ inputs.databasename }}
        
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workspace }}/${{ inputs.outputfilename }}
   
      #- name: check output file name
      #  run: echo "This is the output filename $github.workspace / $inputs.outputfilename"
