name: Re-usable Workflow file 2
on:
  workflow_call:
    inputs:
      slqserverfullname:
        required: true
        type: string
      databasename:
        required: true
        type: string
      outputfilename:
        required: true
        type: string
   
jobs:
  Reusabble_fil_2:   
  
   runs-on: windows-latest
   #environment: 'Development'
   defaults:
      run:
        shell: bash
   steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3  
        
      - name: Add sqlpackage to PATH
        uses: coreywebber/setup-sqlpackage@v1
        with:
          sql-version: 14
              
      - name: Build dacpac
        run: sqlpackage.exe /TargetFile:${{ github.workspace }}/${{ inputs.outputfilename }} /Action:Extract /SourceServerName:${{ slqserverfullname }} /SourceDatabaseName:${{ databasename }}
        # run: sqlpackage.exe /TargetFile:%1 /Action:Extract /SourceServerName:%2 /SourceDatabaseName:%3
        
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workspace }}/${{ inputs.outputfilename }}
   
   #   create dacpac using sqlpackage for current server database
   #   - name: Build dacpac from SQL Server Database
   #     env:
   #       outputfile: ${{ github.workspace }}/svr_GITHUB_ACTIONDB_TESTING.dacpac
   #       server:  ${{ inputs.slqserverfullname }}
   #       databasename: ${{ inputs.databasename }}
   #     run: ./exec_sqlpackage_build_dacpac_from_sql.bat ${{ env.outputfile }} ${{ env.server }} ${{ env.databasename }}
        
   # steps:
   #  - name: See if ref name is still avaliable
   #    run: echo "This is in reusablee file 2 - what branch does it think its using  $GITHUB_REF_NAME"
       
   #  - name: Check inputvalue_one - reusable file 2
   #    run: echo "This is in reusable file 2 - what value is in var inputvalue_one  ---   ${{ inputs.inputvalue_one }} "

