name: Re-usable Workflow file 2
on:
  workflow_call:
    inputs:
      inputvalue_one:
        required: true
        type: string
      inputvalue_two:
        required: true
        type: string

   
jobs:
  Reusabble_fil_2:   
  
   runs-on: windows-latest
   #environment: 'Development'
   defaults:
      run:
        shell: bash

  # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
     - name: See if ref name is still avaliable
       run: echo "This is in reusablee file 2 - what branch does it think its using  $GITHUB_REF_NAME"
       
     - name: Check inputvalue_one - reusable file 2
       run: echo "This is in reusable file 2 - what value is in var inputvalue_one  ---   ${{ inputs.inputvalue_one }} "
       
     - name: Check inputvalue_two - reusable file 2
       run: echo "This is in reusable file 2- what value is in var inputvalue_two  ---   ${{ inputs.inputvalue_two }}"
