name: create_sql_delta_script
on:
  workflow_call:
    inputs:
      sourcefile:
        required: true
        type: string
      targetfile:
        required: true
        type: string
      targetdatabasename:
        required: true
        type: string
      sqloutputfileandpathname:
        required: true
        type: string      
   
jobs:
  Create_delta_script_from_dacpacs:   
  
   runs-on: self-hosted 
   defaults:
      run:
        shell: cmd
   steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        
      - name: Add sqlpackage to PATH
        uses: coreywebber/setup-sqlpackage@v1
        with:
          sql-version: 14
          
      - name: Build delta script
        run: sqlpackage.exe /Action:Script /SourceFile:${{ inputs.sourcefile }} /TargetFile:${{ inputs.targetfile }} /TargetDatabaseName:${{ inputs.targetdatabasename }} /OutputPath:${{ inputs.sqloutputfileandpathname }} /p:DropObjectsNotInSource=TRUE /p:ScriptDatabaseOptions=False /p:DoNotDropObjectTypes=Sequences;DatabaseRoles;Permissions;Credentials;ColumnEncryptionKeys;ColumnMasterKeys;Certificates;RoleMembership;SymmetricKeys;Users;Audits;CryptographicProviders;DatabaseAuditSpecifications;DatabaseScopedCredentials;Logins;ServerRoleMembership;ServerRoles /p:ExcludeObjectTypes=Aggregates;ApplicationRoles;Assemblies;AsymmetricKeys;BrokerPriorities;Certificates;ColumnEncryptionKeys;ColumnMasterKeys;Contracts;DatabaseRoles;DatabaseTriggers;Defaults;ExtendedProperties;ExternalDataSources;ExternalFileFormats;ExternalTables;Filegroups;FileTables;FullTextCatalogs;FullTextStoplists;MessageTypes;PartitionFunctions;PartitionSchemes;Permissions;Queues;RemoteServiceBindings;RoleMembership;Rules;ScalarValuedFunctions;SearchPropertyLists;SecurityPolicies;Sequences;Services;Signatures;StoredProcedures;SymmetricKeys;Synonyms;TableValuedFunctions;UserDefinedDataTypes;UserDefinedTableTypes;ClrUserDefinedTypes;Users;XmlSchemaCollections;Audits;Credentials;CryptographicProviders;DatabaseAuditSpecifications;DatabaseScopedCredentials;Endpoints;ErrorMessages;EventNotifications;EventSessions;LinkedServerLogins;LinkedServers;Logins;Routes;ServerAuditSpecifications;ServerRoleMembership;ServerRoles;ServerTriggers
      
      #run: sqlpackage.exe /TargetFile:${{ github.workspace }}/${{ inputs.outputfilename }} /Action:Extract /SourceServerName:${{ inputs.slqserverinstancename }}\${{ inputs.slqservername }} /SourceDatabaseName:${{ inputs.databasename }}
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ inputs.sqloutputfileandpathname }}
