name: Re-usable Workflow file 1
on:
  workflow_call:
    inputs:
      inputvalue_one:
        required: false
        type: string
  
jobs:
    check-secret:
    runs-on: windows-2019
    needs: [build]
    outputs:
      my-key: ${{ steps.my-key.outputs.defined }}
    steps:
        - id: my-key
          if: "${{ env.MY_KEY != '' }}"
          run: echo "::set-output name=defined::true"
          env:
              MY_KEY: ${{ secrets.TARGETDATABASE1 }}
              
  Run_reusable_secret_test:   
  
   runs-on: windows-2019
   defaults:
      run:
        shell: bash

  # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
      - uses: actions/checkout@v3
   
      - name: Check inputvalue_one - reusable file 1
        run: echo "This is in reusable file 1 - what value is in var inputvalue_one  ---   ${{ inputs.inputvalue_one }} "
       
      - name: Echo Baad Secret
        run: echo "${{ secrets.badsecret }}"
