name: Re-usable Workflow file 1
on:
  workflow_call:
    inputs:
      inputvalue_one:
        required: false
        type: string
  
jobs:
    check-secret:
      runs-on: self-hosted # windows-latest
      outputs:
        my-key: ${{ steps.my-key.outputs.defined }}
      steps:
          - id: my-key
            if: "${{ env.MY_KEY != '' }}"
            run: echo "::set-output name=defined::true"
            env:
                MY_KEY: ${{ secrets.TARGETDATABASE1 }}
              
    Run_reusable_secret_test:    
     runs-on: self-hosted # windows-2019
    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:

        - name: Echo Baad Secret
          run: echo "${{ secrets.badsecret }}"
