name: Re-usable Workflow file 1
on:
  workflow_call:
    inputs:
      inputvalue_one:
        required: false
        type: string
  
jobs:
  check-secret:
    runs-on: windows-2019 #ubuntu-latest
    outputs:
      my-key: ${{ steps.my-key.outputs.defined }}
    steps:
        - id: my-key
          if: "${{ env.MY_KEY != '' }}"
          run: echo "::set-output name=defined::true"
          env:
              MY_KEY: ${{ secrets.TARGETDATABASE1 }}
              
  CheckSecretValue:
    runs-on: windows-2019 #ubuntu-latest
    steps:
      - name: echo secret
        run: echo "This is my TARGETDATABASE1 return value ${{ secrets.TARGETDATABASE1 }}"       
      
      - name: echo input value
        run: echo "This is my TARGETDATABASE1 return value ${{ inputs.inputvalue_one }}"  
      
  job1:
    runs-on: windows-2019 #ubuntu-latest
    needs: [check-secret]
    if: needs.check-secret.outputs.my-key == 'true'
    steps:
      - run: echo "This command is executed if TARGETDATABASE1 secret IS NOT empty"

      
    
  job2:
    runs-on: windows-2019 #ubuntu-latest
    needs: [check-secret]
    if: needs.check-secret.outputs.my-key != 'true'
    steps:
      - run: echo "This command is executed if TARGETDATABASE1 secret IS empty"           
      
